apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-model
  template:
    metadata:
      labels:
        app: ai-model
    spec:
      containers:
        - name: ai-model
          image: ai-model:latest
          env:
            - name: MINIO_ENDPOINT
              value: "minio:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"

---
apiVersion: v1
kind: Service
metadata:
  name: ai-model
spec:
  selector:
    app: ai-model
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
