apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: airflow-webserver
          image: apache/airflow:2.7.3
          args:
            - webserver
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryExecutor"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "db+postgresql://airflow:airflow@postgres/airflow"
            - name: AIRFLOW__CELERY__BROKEN_URL
              value: "redis://redis:6379/0"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
spec:
  selector:
    app: airflow-webserver
  ports:
    - ports: 8080
      targetPort: 8080
  type: NodePort
